### ISSUE TITLE
build fails on OS X 10.11 El Capitan with rbenv and Homebrew

### ISSUE THREAD

**Issue by hakamadare** [cloudfoundry/bosh-aws-cpi-release#30]
Hello folks!  I'm following [this document](http://docs.cloudfoundry.org/deploying/aws/setup_bosh_aws.html) and during step 2 I repeatedly get the following error:

```
$ bosh-init deploy ./bosh.yml
Deployment manifest: '/Users/rk/deployments/rk-stage-paas/bosh.yml'
Deployment state: '/Users/rk/deployments/rk-stage-paas/bosh-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bosh-aws-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:00)

Started installing CPI
  Compiling package 'ruby_aws_cpi/a5b66d011ce1b31642ff148ea2c9097af65ff78c'... Finished (00:00:00)
  Compiling package 'bosh_aws_cpi/d7ffe4e7cd4cc233372185d8fd9374b737c3320a'... Failed (00:00:03)
Failed installing CPI (00:00:03)

Command 'deploy' failed:
  Installing CPI:
    Compiling job package dependencies for installation:
      Compiling job package dependencies:
        Compiling package:
          Running command: 'bash -x packaging', stdout: 'Installing rake 10.3.2
Installing CFPropertyList 2.3.1
Installing addressable 2.3.8
Installing json 1.8.3
Installing mini_portile 0.6.2

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/bin/ruby extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/bin/ruby
    --help
    --clean
    --use-system-libraries
/Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- openssl (LoadError)
    from /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/lib/ruby/2.1.0/net/https.rb:22:in `<top (required)>'
    from /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:3:in `<top (required)>'
    from /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from extconf.rb:395:in `<main>'


Gem files will remain installed in /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/bosh_aws_cpi/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.6.2/ext/nokogiri/gem_make.out
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.
', stderr: '+ set -e -x
+ BOSH_PACKAGES_DIR=/Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages
+ cp -a bosh_aws_cpi/Gemfile bosh_aws_cpi/Gemfile.lock bosh_aws_cpi/bin bosh_aws_cpi/bosh_aws_cpi.gemspec bosh_aws_cpi/lib bosh_aws_cpi/scripts bosh_aws_cpi/spec bosh_aws_cpi/vendor /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/bosh_aws_cpi
+ bundle_cmd=/Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/bin/bundle
+ cd /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/bosh_aws_cpi
+ /Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/bin/bundle install --local --no-prune --deployment
':
            exit status 5
```

I provided the required OpenSSL version by installing Homebrew's `openssl` package and linking it into place with `brew link --force openssl`.  Having done this, I can build Nokogiri 1.6.6.2 on this system:

```
$ gem list --local nokogiri

*** LOCAL GEMS ***

nokogiri (1.6.6.2)
```

However, it looks like the bosh-aws-cpi build script isn't correctly finding the necessary dependencies in my environment.  What's the recommended procedure for using this package on OS X 10.11?

**Comment by allomov** [comment]
Hey, @hakamadare. 

The main problem of OS X environment is that [Apple stopped shipping openssl as a system library](http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html) in 2015.

It appears that bundle doesn't see openssl library, because `bosh-aws-cpi-release` uses its own ruby and bundle (in your case they are located somewhere in `/Users/rk/.bosh_init/installations/d93aa675-d3f6-4371-5a8b-e704073bbc8f/packages/ruby_aws_cpi/bin`). bosh-init [cuts all environment variables](https://github.com/cloudfoundry/bosh-init/blob/775439ca87b98828a6ca9e0ebbf029ab7c0c72cf/installation/pkg/compiler.go#L95-L101) you have, so you can't specify `PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig"` as a solution. 

The easiest solution for you would be running the deployment from jumpbox VM with Linux. You can use following tools [allomov/ansible-role-bosh-jumpbox](https://github.com/allomov/ansible-role-bosh-jumpbox) or [Infra-Red/bosh-jumpbox](https://github.com/Infra-Red/bosh-jumpbox), to easier setup your jumpbox environemnt

**Comment by allomov** [comment]
I just tried this on my OS X and I can confirm that the problem exists.

**Comment by allomov** [comment]
The quick solution for me was to update bosh-init to prevent it isolating environment variables by setting `UseIsolatedEnv` field to false, [like this](https://github.com/cloudfoundry/bosh-init/compare/master...allomov:stop-isolate-env). After that I was able to run `bosh-init deploy` with the following command:
```
PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig" bosh-init deploy microbosh.yml
```

**Comment by allomov** [comment]
@cppforlife do you think it is acceptable to add PR to prevent isolating env to bosh-init to cope such problems? or should aws-cpi team add openssl package especially for OS X?

**Comment by hakamadare** [comment]
@allomov thanks for looking at this!  i had also been thinking of running bosh-init from a container.

**Comment by cppforlife** [comment]
hmmm. @hakamadare i m not sure why you have to do that. i just tried it on 10.11 with `brew link --force openssl` and it seemed to work. are you saying that after you did brew link ... command it still doesnt work?

@allomov im not sure it's a good idea, since other env vars might affect configuration in a different way which would not be deterministic. may be we should change the CPI to detect it?

**Comment by hakamadare** [comment]
@cppforlife correct, even after `brew link --force openssl` i encountered the same error.

**Comment by ljfranklin** [comment]
@hakamadare @allomov sorry for letting this sit for so long. We're got a story coming up to remove nokogiri entirely as it causes so many headaches, which should fix this issue: https://www.pivotaltracker.com/story/show/128880809
